# METADATA FOR CML-ACTIONS
name: CML-Actions
description : This is a simple custom template for CML workflow for Github Actions
icon: box
color: gray-dark

# CONDITION FOR CML WORKFLOW
on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

# CML WORKFLOW
jobs:
    build:
        runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: install_os_dependencies
    - run: apt install python3 && apt install python3-pip
    
    - name: install_py_dependencies
    - run: python3 -m pip3 install -r requirements.txt
    
    - name: Run file
    - run: python3 main.py
    
    
