# METADATA FOR CML-ACTIONS
name: CML-Actions
description : This is a simple custom template for CML workflow for Github Actions

branding:
    icon: box
    color: gray-dark

# CONDITION FOR CML WORKFLOW
on:
    push:
        branches: [ $default-branch ]
    pull_request:
        branches: [ $default-branch ]

# CML WORKFLOW
jobs:
    build:
        runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Install OS Dependencies
    - run: apt install python3 && apt install python3-pip
    
    - name: Install Python Dependencies
    - run: python3 -m pip3 install -r requirements.txt
    
    - name: Download Dataset source
    - run: wget "DATASET URL"

    - name: Run file
    - run: python3 main.py
    
    
